StMatic documentation
Shard-Labs/PoLido-docs pull request #1
Opened 2022-02-03 06:08 UTC by mayorcoded

This PR contains the documentation updates for StMatic.

2022-02-03 09:19 UTC, Jakic007 commented
We should rename Lido Matic -> StMATIC to comply with actual smart contract names.

2022-02-03 12:47 UTC, mayorcoded commented
> We should rename Lido Matic -> StMATIC to comply with actual smart contract names.

This has been done

2022-02-03 19:53 UTC, idirall22 requested changes

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +Returns the total staked across all validators
Returns the total delegated MATICs across all validators.

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +Returns the total staked across all validators
stake is for an Operator but in stMatic contract we delegate to a validator

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +### convertStMaticToMatic
convertStMaticToMatic()

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +### convertMaticToStMatic
convertMaticToStMatic()

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +Send MATIC to the StMATIC contract and mints `stMATIC` to msg.sender
Send MATIC to the StMATIC contract and mints `stMATIC` to msg.sender. The user has first to approve the amount to the StMATIC contract.

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +| `_amount` | `uint256` | Amount to withdraw. |
Amount to withdraw in stMATIC

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +Allows withdrawal requests to be made from validators or the StMatic contract
Allows users to request withdrawal of an amount of Matic tokens depending on the amount submitted of stMATIC. This will mint a Lido NFT token which can be used later to claim the amount.

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +Delegates the MATIC deposited into the StMatic contract equally to the validators
Delegate the deposited tokens into the StMatic contract between Lido's active operators. The tokens are delegated based on the operator's maxDelegationLimit factor.

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +Allows users claim their tokens from the validators. This requires that the user has a pending withdrawal request
Allows users to claim their tokens from the validators. This requires user to have an NFT that was minted during the requestWithdraw transaction.

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +Distributes rewards claimed from validators to their operators
Distribute rewards accumulated by lido validators. 90% of rewards are buffered and redelegated. 10% is distributed between DAO(2.5%), insurance(2.5%), and active operators(5%).

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +Allows a node operator withdraw the amount staked to a validator
Allows the NodeOperatorRegistry contract to claim the total amount delegated to a validator share.

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +| `_validatorShare` | `address` | Address of the validator proxy. |
Address of the validator share.

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +Claims tokens frm the validator and sends them to the StMatic contract
Claim and transfer the tokens from a spécific validator share contract to the StMATIC contract. This requires a valid Lido NFT token.

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +| `_tokenId` | `uint256` | Token ID of a pending withdrawal request. |
NFT Token ID...

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +| `_amount` | `uint256` | Amount to submit |
Amount to submit in MATIC

2022-02-03 19:53 UTC, idirall22 commented on docs/contracts/StMatic.md
> +Returns the liquid reward the StMatic contract has in a validator
Returns the reward accumulated by the StMATIC contract in a specific validator share.

2022-02-03 20:19 UTC, idirall22 commented
@mayorcoded Please make sure all the functions are documented.

2022-02-04 12:02 UTC, Jakic007 commented on docs/contracts/StMatic.md
>  - [Source code](https://github.com/Shard-Labs/PoLido/blob/main/contracts/LidoMatic.sol)
Fix this link

2022-02-04 12:06 UTC, Jakic007 requested changes
Replace "PoLido" with "Lido for Polygon".
Replace "Lido Matic contract" with "StMATIC contract"

2022-02-04 12:06 UTC, Jakic007 commented on docs/contracts/StMatic.md
>  - [Deployed contract](https://etherscan.io/address/0xae7ab96520de3a18e5e111b5eaab095312d7fe84)
Remove the link until we launch

2022-02-08 10:53 UTC, Jakic007 requested changes

2022-02-08 10:53 UTC, Jakic007 commented on docs/contracts/StMatic.md
> +tokens inside PoLido system. It is a non-rebasable token, which means that the amount of tokens in the user's wallet is
Replace PoLido system with Lido for Polygon system

2022-02-10 12:22 UTC, Jakic007 approved these changes

2022-02-10 13:25 UTC, idirall22 approved these changes
LGTM

2022-02-10 14:55 UTC, merged